server:
  port: 9000
spring:
  application:
    # 当前服务的名称：注册到注册
    name: msc-alibaba-getway-config
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 121.43.114.196:8845
    gateway:
      discovery:
        locator:
          # 配置开启与DiscoveryClient整合
          enabled: true
      routes:
        # 动态路由配置：路由id# 配置Path断言工厂1，路由到consumer
        - id: ribbon_route1
        # 路由uri地址, loadbalancer://服务名称
          uri: lb://msc-alibaba-consumer
          predicates:
            # 拦截所有提供者的请求到提供者集群服务
            - Path=/consumer/shop/**
        # 配置Path断言工厂2，路由到provider
        - id: ribbon_route2
            # 路由uri地址, loadbalancer://服务名称
          uri: lb://msc-alibaba-producer
          predicates:
              # 拦截所有提供者的请求到提供者集群服务
            - Path=/provider/shop/**
            -
        # 添加前缀 过滤器
        - id: prefixPath_filter
          uri: lb://msc-alibaba-producer
          predicates:
            #            # 拦截所有请求
            - Path=/**
          filters:
            - PrefixPath=/consumer
        # 添加前缀 过滤器
        - id: stripPrefix_filter
          uri: http://localhost:8080
          predicates:
            - Path=/**
          filters:
            - StripPrefix=2
        # http://127.0.0.1:9000/depart/get/1                   --> http://127.0.0.1:8080/depart/get/1
        # http://localhost:9000/depart/get/1                   --> http://localhost:8080/consumer/depart/get/1
        # 注意需要将之前的配置移出
        # http://localhost:9000/api/goods/consumer/depart/get/1 --> http://localhost:8080/consumer/depart/get/1