server:
  port: 9000
spring:
  application:
    # 当前服务的名称：注册到注册
    name: msc-alibaba-getway-config
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 121.43.114.196:8845
    gateway:
      discovery:
        locator:
          # 配置开启与DiscoveryClient整合
          enabled: true
      routes:
        # 动态路由配置：路由id# 配置Path断言工厂1，路由到consumer
        - id: ribbon_route1
        # 路由uri地址, loadbalancer://服务名称
          uri: lb://msc-alibaba-consumer
          predicates:
            # 拦截所有提供者的请求到提供者集群服务
            - Path=/consumer/shop/**
        # 配置Path断言工厂2，路由到provider
        - id: ribbon_route2
            # 路由uri地址, loadbalancer://服务名称
          uri: lb://msc-alibaba-producer
          predicates:
              # 拦截所有提供者的请求到提供者集群服务
            - Path=/provider/shop/**
