server:
  port: 8099
spring:
  application:
    # 当前服务的名称：注册到注册
    name: msc-alibaba-getway-showinfo
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 121.43.114.196:8845
    gateway:
      discovery:
        locator:
          # 配置开启与DiscoveryClient整合
          enabled: true
  redis:
    #数据库索引
    database: 0
    host: 121.43.114.196
    port: 16376
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
    timeout: 10000

